# 第二次课作业

（1）创建一个1到10的数组，然后逆序输出。

In [1]:
print("hello world")

hello world


In [6]:
L=[i for i in range(1,11)]
L[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。

In [2]:
import numpy as np
a = np.ones(20,dtype="int")

In [3]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
b=a.reshape(4,5)

In [5]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
b.T

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)

In [10]:
np.random.random((3,3,3))

array([[[0.96545339, 0.53563315, 0.46663852],
        [0.67652548, 0.95654096, 0.90497171],
        [0.65328898, 0.04323294, 0.93645183]],

       [[0.6549559 , 0.54388521, 0.30286279],
        [0.6776196 , 0.49284399, 0.16770256],
        [0.23124545, 0.08814161, 0.44852006]],

       [[0.83247132, 0.43181601, 0.16751028],
        [0.08356996, 0.76211726, 0.78811712],
        [0.04920764, 0.83525164, 0.37537905]]])

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

In [13]:
a = np.random.randint(1,11,10)
a

array([4, 2, 3, 8, 3, 1, 9, 8, 5, 4])

In [14]:
a.sort()

In [15]:
a

array([1, 2, 3, 3, 4, 4, 5, 8, 8, 9])

In [16]:
a.min()

1

In [17]:
a.max()

9

In [18]:
a.var()

6.8100000000000005

（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [23]:
a[np.where(a%2==1)]

array([1, 3, 3, 5, 9])

In [24]:
a[a%2==1]

array([1, 3, 3, 5, 9])

（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [27]:
a = np.arange(0,101,5)

In [30]:
type(a)

numpy.ndarray

In [31]:
a.astype('int32')

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [28]:
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [32]:
a = np.random.randint(1,11,10)
a

array([ 9,  3,  5,  2,  8,  9, 10,  5,  4,  8])

In [33]:
a[(a>3)&(a<8)]*= -1
a

array([ 9,  3, -5,  2,  8,  9, 10, -5, -4,  8])

（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [34]:
a = [1,2,3,4,5]
b = np.zeros(9,dtype='int')
b[::2]=a
b

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。

In [35]:
a = np.random.randint(1,10,(5,5))
a

array([[7, 5, 1, 9, 2],
       [3, 1, 6, 7, 3],
       [2, 1, 3, 9, 2],
       [9, 1, 4, 3, 2],
       [2, 4, 4, 2, 3]])

In [36]:
a[[1,0,2,3,4]]

array([[3, 1, 6, 7, 3],
       [7, 5, 1, 9, 2],
       [2, 1, 3, 9, 2],
       [9, 1, 4, 3, 2],
       [2, 4, 4, 2, 3]])

In [37]:
a[:,[1,0,2,3,4]]

array([[5, 7, 1, 9, 2],
       [1, 3, 6, 7, 3],
       [1, 2, 3, 9, 2],
       [1, 9, 4, 3, 2],
       [4, 2, 4, 2, 3]])

（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

In [38]:
a = np.random.randint(1,10,(10,2))
a

array([[1, 8],
       [2, 3],
       [7, 1],
       [9, 8],
       [9, 2],
       [7, 8],
       [2, 5],
       [9, 4],
       [6, 3],
       [7, 4]])

（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

In [39]:
a = np.ones(10,dtype='int')*2
a[4]=1
a

array([2, 2, 2, 2, 1, 2, 2, 2, 2, 2])

（12）创建一个长度为10的随机向量，并求其累计和。

In [40]:
a = np.random.randint(1,10,10).cumsum()

In [41]:
a

array([ 8, 15, 24, 25, 26, 34, 39, 48, 53, 55], dtype=int32)

（13）将数组中的所有奇数替换成-1。

In [46]:
a = np.random.randint(1,10,10)
a[a%2==1]=-1

In [47]:
a

array([-1,  2, -1, -1,  8, -1,  4, -1, -1,  6])

（14）构造两个4乘3的二维数组，按照3种方法进行连接？

In [50]:
a = np.random.randint(1,10,(4,3))
b = np.random.randint(1,10,(4,3))

In [53]:
np.vstack((a,b))

array([[4, 3, 1],
       [6, 4, 7],
       [3, 6, 5],
       [3, 9, 9],
       [4, 2, 1],
       [3, 6, 1],
       [5, 4, 5],
       [7, 6, 7]])

（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [54]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = a-b

In [55]:
c

array([-6,  0, -7,  0, -4,  0, -6,  0, -4, -2])

In [57]:
np.where(c==0)

(array([1, 3, 5, 7], dtype=int64),)

In [58]:
a[c==0]

array([2, 2, 4, 4])

（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])

In [59]:
a=np.array([7,2,10,2,7,4,9,4,9,8])
a[4<a<10]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()